### ISSUE TITLE
Feature Request: Line Thickness

### ISSUE THREAD

**Issue by Edgaras91** [faulandcc/GesturePatternViewXF#3]
Hi,

Could you add line thickness options?
The line is very slim at the moment.
The thickness for both:
LineDrawing
LineDrawn

While drawing its 1 thickness, once connected the points, the line becomes even thicker/slimmer.

**Comment by faulandcc** [comment]
Hi, I added your properties (and some more) to version 1.0.3. Source code is already checked in - nuget package may take some more minutes to release.

The GesturePatternView now supports the following properties:
- TouchPointStrokeWidth
- TouchPointTouchedStrokeWidth
- TouchPointInnerCircleStrokeWidth
- LineDrawingStrokeWidth
- LineDrawnStrokeWidth
