### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by Edgaras91** [faulandcc/GesturePatternViewXF#4]
When adding to the global/portable class (which is .NETStandard,Version=v2.0)

Package 'FaulandCc.XF.GesturePatternView 1.0.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

![image](https://user-images.githubusercontent.com/32236075/60718536-d0a6be00-9f1c-11e9-9f5d-393813808dd0.png)

**Comment by faulandcc** [comment]
That's interesting. I just created a new NetStandard2.0 library and can add a nuget reference to the FaulandCc.XF.GesturePatternView without any problems. Have you tried updating to version 1.0.3?

**Comment by Edgaras91** [comment]
Same
![image](https://user-images.githubusercontent.com/32236075/60718991-33e52000-9f1e-11e9-84fa-aeefe2467d3d.png)

**Comment by Edgaras91** [comment]
I don't have .NETFramework mentioned anywhere, including the project file.
I suspect it might be on nuget's end.

**Comment by faulandcc** [comment]
NuGet uses the .NET Framework 4.6.1 since it cannot find a NetStandard-Version of the lib on the nuget server.

I have to migrate the PCL to NetStandard. Will do that the next days. If you need it immediately, please check out the lib and create a PR. Since it's a warning, you might try to use it anyway.

**Comment by faulandcc** [comment]
OK, I did it now - Version 1.0.4 is now using .Net Standard 2.0. The warning should be gone now. Would be great if you could confirm that.

**Comment by Edgaras91** [comment]
Yes, 1.0.4 resolved it. Thanks for rapid support!
